### ISSUE TITLE
loading PDF error

### ISSUE THREAD

**Issue by wantsci** [fusion-jena/automatic-KG-creation-with-LLM#14]
Hello, when I run the main.py, when reading Pdfs, the following error message will appear, please how to solve this problem
![image](https://github.com/fusion-jena/automatic-KG-creation-with-LLM/assets/113997146/c604257e-5c5d-4dd4-a2da-d80f10ddccbe)

**Comment by Vamsi-Kommineni** [comment]
@wantsci We reran the pipeline again, but we haven't faced any such errors.
