### ISSUE TITLE
Function seems to be imported from nowhere

### ISSUE THREAD

**Issue by educatedpolarbear** [fusion-jena/automatic-KG-creation-with-LLM#19]
Hi, I found this line of code:
```
        csv_file = os.path.join(folder_path, f'{version}', kg_evaluation_filename_format.format(publication_no=publication_no))
```
Line 112, in `create_KG_evaluation_csv.py`
Seems like the kg_evaluation_filename_format was imported from nowhere, does it affect anything?

**Comment by Vamsi-Kommineni** [comment]
@thanhchauns2 kg_evaluation_filename_format was initialized in line 103 in `create_KG_evaluation_csv.py`
