### ISSUE TITLE
Is it possible to create KG for non-English texts?

### ISSUE THREAD

**Issue by fishfree** [fusion-jena/automatic-KG-creation-with-LLM#21]
If not out-of-box, how to modify?
Many thanks!

**Comment by Vamsi-Kommineni** [comment]
Yes, it's possible to create KG for non-English texts. You have to use different LLMs that support the target language. Here are examples LLMs that support other languages: 

- https://huggingface.co/models?language=multilingual
- https://huggingface.co/collections/smcproject/llms-in-non-english-languages-6603a39bf81af72b0627727b

To modify the code, change the `load_llm` function in `helper_functions.py` and `LLM_loader.py` according to the selected LLM.
