### ISSUE TITLE
missing file "../Prompts/Concepts_and_relationships_extraction.txt"

### ISSUE THREAD

**Issue by crownz248** [fusion-jena/automatic-KG-creation-with-LLM#24]
missing file "../Prompts/Concepts_and_relationships_extraction.txt" when running main.py. Using default config.ini
![image](https://github.com/user-attachments/assets/4aeebcd5-bd49-4188-b8ef-b4411390d07b)

**Comment by Vamsi-Kommineni** [comment]
@crownz248 The code has been updated in v2.0
